#!/bin/bash

shopt -s nullglob dotglob; files=(/Applications/Live\ 8.2*); 
latest_live=${files[@]:(-1)}; 

mv /private/tmp/Dark\ Theme.ask "$latest_live/Live.app/Contents/App-Resources/Skins/"

exit 0

