#!/bin/bash

shopt -s nullglob dotglob; files=(/Applications/Live\ 8.2*); 
latest_live=${files[@]:(-1)}; 

mv /private/tmp/darktheme.ask "$latest_live/Live.app/Contents/App-Resources/Skins/Dark Theme.ask"

exit 0

